# Generated by Django 3.2.23 on 2023-11-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20231108_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='start_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
