# Generated by Django 3.2.23 on 2023-11-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_signup_start_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lname',
            new_name='last_name',
        ),
    ]
